server:
  port: 8081
  shutdown: graceful

spring:
  application:
    name: auth-service
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/jaggery_auth?useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${DDL_AUTO:update}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
logging:
  level:
    auth_service: DEBUG